---
title: "Getting Started with flexseq"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started with flexseq}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
if(requireNamespace("immutables", quietly = TRUE)) {
  library(immutables)
} else if(requireNamespace("pkgload", quietly = TRUE)) {
  pkgload::load_all(".", quiet = TRUE)
} else {
  stop("Need either installed 'immutables' or the 'pkgload' package to render this vignette.")
}
```

## Creating sequences

`flexseq` objects are persistent (immutable) sequences.
Each update returns a new object.

```{r}
x <- flexseq(1, 2, 3)
x

x2 <- as_flexseq(letters[1:5])
x2
```

## Indexing

```{r}
x2[[3]]

x3 <- x2[c(1, 3, 5)]
x3
```

## Pushing at either end

```{r}
x4 <- push_back(x2, "f")
x4

x5 <- push_front(x4, "start")
x5
```

## Peeking and popping

```{r}
peek_front(x5)
peek_back(x5)

pf <- pop_front(x5)
pf$element
pf$remaining
```

## Named sequences

```{r}
x_named <- as_flexseq(list(a = 1, b = 2, c = 3))
x_named

x_named[["b"]]
x_named$c
```

## Concatenation

```{r}
x6 <- as_flexseq(4:6)
x7 <- c(x, x6)
x7
```

## Applying a transform

```{r}
x8 <- as_flexseq(1:5)
lapply(x8, function(el) el * 10)
```
