---
title: "Priority Queues"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Priority Queues}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
if(requireNamespace("immutables", quietly = TRUE)) {
  library(immutables)
} else if(requireNamespace("pkgload", quietly = TRUE)) {
  pkgload::load_all(".", quiet = TRUE)
} else {
  stop("Need either installed 'immutables' or the 'pkgload' package to render this vignette.")
}
```

## Creating a priority queue

```{r}
x <- priority_queue("task_a", "task_b", "task_c", priorities = c(3, 1, 2))
x
```

## Peeking at extremes

```{r}
peek_min(x)
peek_max(x)
```

## Popping elements

`pop_min()` and `pop_max()` return both the element and the updated queue.

```{r}
x2 <- pop_min(x)
x2$element
x2$priority
x2$queue
```

## Inserting elements

```{r}
x3 <- insert(x, "task_d", priority = 0)
x3
peek_min(x3)
```

## Persistence

The original queue is unchanged.

```{r}
peek_min(x)
length(x)
```
